In [1]:
import numpy

vector=numpy.array([2,3,4,11])
vector==3

array([False,  True, False, False])

In [2]:
matrix=numpy.array([
    [5,6,7],
    [23,24,11],
    [44,64,24],
])

matrix==24

array([[False, False, False],
       [False,  True, False],
       [False, False,  True]])

In [3]:
vector=numpy.array([24,52,2,2])
equal_to_tow=(vector==2)
print(equal_to_tow)
print(vector[equal_to_tow]) #bool值为索引 


[False False  True  True]
[2 2]


In [4]:
matrix=numpy.array([
    [4,5,6],
    [33,4,5],
    [3,5,1]
])
second_column_4=(matrix[:,1]==4)
print(second_column_4)
print(matrix[second_column_4,:]) #目标值所在行 所有值

[False  True False]
[[33  4  5]]


In [6]:
vector=numpy.array([5,6,6,11])
# equal_to_five_or_eleven=(vector==5)&(vector==11)
equal_to_five_or_eleven=(vector==5)|(vector==11)
print(equal_to_five_or_eleven)
vector[equal_to_five_or_eleven]=50
print(vector)

[ True False False  True]
[50  6  6 50]


In [8]:
matrix=numpy.array([
    [3,4,5],
    [6,2,1],
    [4,2,1]
])
first_column_4=matrix[:,0]==4
print(first_column_4)
matrix[first_column_4,0]=10
print(matrix)

[False False  True]
[[ 3  4  5]
 [ 6  2  1]
 [10  2  1]]


In [9]:
vector=numpy.array(['1','2','3'])
print(vector.dtype)
print(vector)
vector=vector.astype(float) #值类型转换
print(vector.dtype)
print(vector)

<U1
['1' '2' '3']
float64
[1. 2. 3.]


In [14]:
vector=numpy.array([4,5,6,11])
vector.min()
print(help(numpy.sum))

Help on function sum in module numpy.core.fromnumeric:

sum(a, axis=None, dtype=None, out=None, keepdims=<no value>, initial=<no value>)
    Sum of array elements over a given axis.
    
    Parameters
    ----------
    a : array_like
        Elements to sum.
    axis : None or int or tuple of ints, optional
        Axis or axes along which a sum is performed.  The default,
        axis=None, will sum all of the elements of the input array.  If
        axis is negative it counts from the last to the first axis.
    
        .. versionadded:: 1.7.0
    
        If axis is a tuple of ints, a sum is performed on all of the axes
        specified in the tuple instead of a single axis or all the axes as
        before.
    dtype : dtype, optional
        The type of the returned array and of the accumulator in which the
        elements are summed.  The dtype of `a` is used by default unless `a`
        has an integer dtype of less precision than the default platform
        integer.  In t

In [12]:
matrix=numpy.array([
    [2,3,4],
    [34,11,11],
    [34,14,51]
])
matrix.sum(axis=1) 
#1 means that we want to perform the operation on each row
print("*"*40)
matrix.sum(axis=0)
#0 means that we want to perform the operation on each column

****************************************


array([70, 28, 66])

In [15]:
world_alcohol=numpy.genfromtxt('world_alcohol.txt',delimiter=',',dtype=float)
print(world_alcohol)

is_value_empty=numpy.isnan(world_alcohol[:,4])
print(is_value_empty)

world_alcohol[is_value_empty,4]='0'

alcohol_consumption=world_alcohol[:,4]
alcohol_consumption=alcohol_consumption.astype(float)

total_alcohol=alcohol_consumption.sum()
average_alcohol=alcohol_consumption.mean()
print(total_alcohol)
print(average_alcohol)

[[      nan       nan       nan       nan       nan]
 [1.986e+03       nan       nan       nan 0.000e+00]
 [1.986e+03       nan       nan       nan 5.000e-01]
 ...
 [1.987e+03       nan       nan       nan 7.500e-01]
 [1.989e+03       nan       nan       nan 1.500e+00]
 [1.985e+03       nan       nan       nan 3.100e-01]]
[ True False False False False False False False False False False False
 False False False False False False False False False False False False
 False  True False False False False  True False False False False False
 False False False False False False False False False  True False False
 False False False False False False False False False False False False
 False False False False False False False False False False False False
 False False False False False False False False False False False False
  True False False False False False False False False False  True False
 False False False False False False  True False False False False False
 False False False 