In [10]:
import numpy
world_alcohol=numpy.genfromtxt('world_alcohol.txt',delimiter=',',dtype=str)
print(type(world_alcohol))
print(world_alcohol)
print(help(numpy.genfromtxt)) #查看函数使用方法

<class 'numpy.ndarray'>
[['Year' 'WHO region' 'Country' 'Beverage Types' 'Display Value']
 ['1986' 'Western Pacific' 'Viet Nam' 'Wine' '0']
 ['1986' 'Americas' 'Uruguay' 'Other' '0.5']
 ...
 ['1987' 'Africa' 'Malawi' 'Other' '0.75']
 ['1989' 'Americas' 'Bahamas' 'Wine' '1.5']
 ['1985' 'Africa' 'Malawi' 'Spirits' '0.31']]
Help on function genfromtxt in module numpy.lib.npyio:

genfromtxt(fname, dtype=<class 'float'>, comments='#', delimiter=None, skip_header=0, skip_footer=0, converters=None, missing_values=None, filling_values=None, usecols=None, names=None, excludelist=None, deletechars=None, replace_space='_', autostrip=False, case_sensitive=True, defaultfmt='f%i', unpack=None, usemask=False, loose=True, invalid_raise=True, max_rows=None, encoding='bytes')
    Load data from a text file, with missing values handled as specified.
    
    Each line past the first `skip_header` lines is split at the `delimiter`
    character, and characters following the `comments` character are discar

In [7]:
vector=numpy.array([5,6,7,8,34]) #一维
matrix=numpy.array([[4,5,7,6],[2,4,52,2],[12,45,12,45]]) #二维
print(vector)
print(matrix)

[ 5  6  7  8 34]
[[ 4  5  7  6]
 [ 2  4 52  2]
 [12 45 12 45]]


In [11]:
vector=numpy.array([1,2,3,4])
print(vector.shape) #行和列
matrix=numpy.array([[1,2,3,4],[5,6,6,7]])
print(matrix.shape) #查看结构

(4,)
(2, 4)


In [19]:
'''
numpy 传入的数据必须相同类型
'''
import numpy
numbers=numpy.array([1,2,3,4])
print(numbers)
print(numbers.dtype)
print("*"*10)
numbers=numpy.array([1,2,3,4.0])
print(numbers.dtype)
print("*"*10)
numbers=numpy.array([1,2,3,'4'])
print(numbers.dtype)

[1 2 3 4]
int32
**********
float64
**********
<U11


In [21]:
world_alcohol=numpy.genfromtxt('world_alcohol.txt',delimiter=',',dtype=str,skip_header=1)
print(world_alcohol)

uruguay_other_1986=world_alcohol[1,4]
third_country=world_alcohol[2,2] #取某一位值
print(uruguay_other_1986)
print(third_country)


[['1986' 'Western Pacific' 'Viet Nam' 'Wine' '0']
 ['1986' 'Americas' 'Uruguay' 'Other' '0.5']
 ['1985' 'Africa' "Cte d'Ivoire" 'Wine' '1.62']
 ...
 ['1987' 'Africa' 'Malawi' 'Other' '0.75']
 ['1989' 'Americas' 'Bahamas' 'Wine' '1.5']
 ['1985' 'Africa' 'Malawi' 'Spirits' '0.31']]
0.5
Cte d'Ivoire


In [23]:
vector=numpy.array([5,6,7,8])
print(vector[0:3]) #切片  [) 左闭右开

[5 6 7]


In [37]:
matrix=numpy.array([
    [5,6,7],
    [2,355,4],
    [33,456,11]
])
# 行 列
print("*"*30)
print(matrix[1:,:])
print("*"*30)
print(matrix[:,2])
print("*"*30)
print(matrix[:,0:2])
print("*"*30)
print(matrix[1:3,0:2])

******************************
[[  2 355   4]
 [ 33 456  11]]
******************************
[ 7  4 11]
******************************
[[  5   6]
 [  2 355]
 [ 33 456]]
******************************
[[  2 355]
 [ 33 456]]
